language: java

jdk:
    - oraclejdk8
    
android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23

notifications:
    email:
        - maninwindow@hotmail.com
        
sudo: required

install:
    # Ensure Gradle wrapper is executable, download wrapper and show version
    - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v

    # Download and show android dependencies
    - ./gradlew androidDependencies

script:
    - ./gradlew library:check library:assemble
