language: android

jdk:
    - oraclejdk8
    
android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23

notifications:
    email:
        - maninwindow@hotmail.com
        
sudo: required

before_script:
 - chmod +x gradlew
